- name: Wait for MySQL container to become ready
  wait_for:
    host: "localhost"
    port: 3307
    delay: 20
    timeout: 120


- name: Copy backup.sql from host to MySQL container
  command: docker cp /home/solaruser/solarsystem/Docker/backup_file_CR.sql mysql:tmp/backup_file.sql

- name: Import backup.sql into MySQL container
  shell: docker exec -i mysql bash -c 'cat /tmp/backup_file.sql | mysql -u root -psgt2023 solar_system'
  args:
    executable: /bin/bash
