- name: Wait for MySQL container to become ready
  wait_for:
    host: "localhost"
    port: 3308
    delay: 20
    timeout: 120


- name: Copy backup.sql from host to MySQL container
  command: docker cp /home/solaruser/solarsystem/backup_file.sql docker_db_1:tmp/backup_file.sql

- name: Import backup.sql into MySQL container
  shell: docker exec -i docker_db_1 bash -c 'cat /tmp/backup_file.sql | mysql -u root -SGT2023 db'
  args:
    executable: /bin/bash
