openapi: 3.0.0
info:
  title: Solar system
  description: Information about Solar system
  version: 1.0.0
servers:
  - url: /api

paths:
  /planets:
    get:
      summary: Get all information about planets
      operationId: api.read_all
      responses:
        "200":
          description: Successfully retrieved
        "404":
          description: Something is wrong
    post:
      summary: Create a new planet
      operationId: api.create_planet
      requestBody:
        description: Create a new planet
        content:
          application/json:
            schema:
              x-body-name: planet
              $ref: "#/components/schemas/Planet"
      responses:
        "201":
          description: Successfully created
        "409":
          description: Planet with provided name already exists
  /planets/{name}:
    get:
      summary: Read one planet
      operationId: api.read_one_planet
      parameters:
        - $ref: "#/components/parameters/name"
      responses:
        "200":
          description: Successfully read one planet
    delete:
      summary: Delete one planet
      operationId: api.delete_planet
      parameters:
        - $ref: "#/components/parameters/name"
      responses:
        "200":
          description: Successfully deleted planet
        "404":
          description: Planet does not exist
    put:
      summary: Update one planet
      operationId: api.update_planet
      parameters:
        - $ref: "#/components/parameters/name"
      requestBody:
        description: Create a new planet
        content:
          application/json:
            schema:
              x-body-name: planet
              $ref: "#/components/schemas/Planet"
      responses:
        "200":
          description: Successfully updated planet information
components:
  schemas:
    Planet:
      required:
        - name
      properties:
        name:
          type: string
        orbital_period_days:
          type: string
        average_speed_kms:
          type: string
        satellites:
          type: string
        mean_radius:
          type: string
        temperature_c:
          type: string
  parameters:
    name:
      name: name
      description: planet name
      in: path
      required: true
      schema:
        type: string
